<x-app-layout>
    @php($gatewayConfirmed = $items->filter(fn ($item) => $item->order->payment_method === 'demo_gateway' && $item->order->payment_status === 'paid')->sum('price'))
    <x-slot name="header"><h1 class="font-bold text-2xl">แดชบอร์ดร้านค้า</h1></x-slot>
    <div class="max-w-6xl mx-auto space-y-6 p-6">
        <section class="card p-6"><p>สถานะการยืนยันตัวตน: <b>{{ $profile?->status ?? 'ยังไม่ส่งข้อมูล' }}</b> <a class="ml-3 text-indigo-600" href="{{ route('dealer.kyc') }}">จัดการข้อมูลร้านและพร้อมเพย์</a></p><div class="mt-4"><p class="text-sm text-slate-400">ยอดที่ระบบสาธิตยืนยันแล้ว</p><p class="mt-1 text-2xl font-bold text-emerald-700">฿{{ number_format($gatewayConfirmed,2) }}</p><p class="mt-1 text-xs text-slate-500">ข้อมูลการชำระเงินในโหมดสาธิต</p></div></section>

        <section class="card p-6"><h2 class="font-bold text-slate-900">รายการชำระเงินและการจัดส่ง</h2>@forelse($items as $item)<div class="border-b py-5 last:border-0"><div class="flex flex-wrap justify-between gap-2"><div><b class="text-slate-900">{{ $item->product->name }}</b><p class="mt-1 text-sm text-slate-500">ลูกค้า: {{ $item->order->customer->name }} · คำสั่งซื้อ #{{ $item->order_id }}</p><p class="mt-1 text-xs font-semibold text-red-300">{{ $item->order->payment_method === 'demo_gateway' ? 'ระบบรับชำระเงิน (สาธิต)' : 'พร้อมเพย์ โอนตรงเข้าร้านค้า' }}</p></div><span class="text-sm font-semibold {{ $item->order->payment_status === 'paid' ? 'text-emerald-700' : 'text-amber-700' }}">{{ $item->order->payment_status === 'paid' ? 'ระบบยืนยันแล้ว' : 'รอระบบยืนยัน' }}</span></div>
            <a href="{{ route('dealer.orders.show', $item->order) }}" class="mt-3 inline-flex min-h-10 items-center rounded-lg border border-red-500/35 bg-red-500/10 px-3 text-sm font-semibold text-red-300 hover:bg-red-500/20">ดูรายละเอียดคำสั่งซื้อ</a>
            @if($item->order->payment_slip_path)<div class="mt-3 flex flex-wrap items-center gap-3"><a href="{{ asset('storage/'.$item->order->payment_slip_path) }}" target="_blank" class="btn-secondary min-h-9 px-3">ดูสลิปการโอน</a>@if($item->order->slip_status === 'pending')<form method="POST" action="{{ route('dealer.payment-slip.verify', $item->order) }}">@csrf @method('PATCH')<button class="rounded bg-emerald-600 px-4 py-2 text-sm font-bold text-white">ยืนยันสลิป</button></form>@endif</div>@endif
            @if($item->delivery_status === 'pending' && $item->order->payment_status === 'paid')<form class="mt-3 flex flex-wrap gap-2" method="POST" action="{{ route('dealer.shipping.update',$item) }}">@csrf @method('PATCH')<input required name="tracking_number" placeholder="เลขพัสดุ" class="rounded border-gray-300"><button class="text-indigo-600">บันทึกการจัดส่ง</button></form>@elseif($item->delivery_status === 'pending')<p class="mt-3 text-sm text-slate-500">รอระบบยืนยันการชำระเงินก่อนเริ่มจัดส่ง</p>@endif</div>@empty<p class="mt-3 text-gray-500">ยังไม่มีรายการ</p>@endforelse</section>
    </div>
</x-app-layout>
