<x-app-layout>
    <x-slot name="header"><h1 class="font-bold text-2xl">{{ isset($sourceProduct) ? 'สร้างรายการใหม่จากสินค้าเดิม' : ($product->exists ? 'แก้ไขสินค้า' : 'เพิ่มสินค้า') }}</h1></x-slot>
    @php($categories = ['desktop' => 'Desktop / Mini PC', 'laptop' => 'Laptop', 'cpu' => 'CPU', 'gpu' => 'GPU / การ์ดจอ', 'ram' => 'RAM', 'storage' => 'SSD / HDD', 'motherboard' => 'Mainboard', 'psu' => 'Power Supply', 'case' => 'Case', 'monitor' => 'Monitor', 'accessory' => 'อุปกรณ์เสริม'])
    @php($specs = old('specs', $product->specs ?: ['cpu' => '', 'ram' => '']))
    @php($stockQuantity = old('stock_quantity', $product->exists ? $product->stock_quantity : 1))
    @php($copiedImages = $copiedImages ?? collect())
    <form x-data="{ category: '{{ old('category', $product->category ?? 'desktop') }}' }" method="POST" enctype="multipart/form-data" action="{{ $product->exists ? route('dealer.products.update', $product) : route('dealer.products.store') }}" class="max-w-3xl mx-auto space-y-4 rounded-2xl bg-white p-6 shadow">@csrf
        @if ($product->exists) @method('PUT') @endif
        @if (isset($sourceProduct))
            <section class="rounded-xl border border-red-500/30 bg-red-500/10 p-4" aria-labelledby="copy-product-heading"><h2 id="copy-product-heading" class="font-bold text-slate-900">สร้างต่อจากรายการที่ขายแล้ว</h2><p class="mt-1 text-sm text-slate-600">คัดลอกข้อมูลและรูปจาก “{{ $sourceProduct->name }}” แล้ว กรุณาระบุจำนวนใหม่ก่อนบันทึก</p></section>
        @endif
        @if ($errors->any())<div class="rounded-xl border border-red-500/60 bg-red-500/10 p-4 text-sm text-red-300"><p class="font-bold">บันทึกสินค้าไม่สำเร็จ</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div><label class="mb-1 block text-sm font-semibold text-slate-900" for="name">ชื่อสินค้า</label><input id="name" required name="name" value="{{ old('name', $product->name) }}" placeholder="เช่น RTX 4070 Super" class="w-full rounded-xl">@error('name')<p class="mt-1 text-xs text-red-400">{{ $message }}</p>@enderror</div>
        <div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><div><label class="mb-1 block text-sm font-semibold text-slate-900">หมวดสินค้า</label><select x-model="category" required name="category" class="w-full rounded-xl">@foreach ($categories as $value => $label)<option value="{{ $value }}" @selected(old('category', $product->category ?? 'desktop') === $value)>{{ $label }}</option>@endforeach</select></div><div><label class="mb-1 block text-sm font-semibold text-slate-900">ราคา</label><input required type="number" step="0.01" min="1" name="price" value="{{ old('price', $product->price) }}" placeholder="ราคา" class="w-full rounded-xl"></div><div><label for="stock_quantity" class="mb-1 block text-sm font-semibold text-slate-900">จำนวนคงเหลือ</label><input id="stock_quantity" required type="number" min="0" max="9999" step="1" inputmode="numeric" name="stock_quantity" value="{{ $stockQuantity }}" aria-describedby="stock_quantity_help" class="w-full rounded-xl"><p id="stock_quantity_help" class="mt-1 text-xs text-slate-500">ระบุ 0 เมื่อสินค้าหมด ระบบจะไม่แสดงสินค้าหน้าซื้อ</p></div></div>
        <div x-cloak x-show="['desktop', 'laptop'].includes(category)"><p class="mb-2 text-sm font-semibold text-slate-900">สเปกสินค้า</p><p class="mb-2 text-xs text-slate-500">กรอกค่าของสเปก เช่น CPU: Core i5-12400F หรือ RAM: 16GB DDR4</p><div class="space-y-2">@foreach($specs as $key => $value)<div class="grid grid-cols-[120px_1fr] gap-2"><input value="{{ $key }}" disabled class="rounded-xl border-gray-700 bg-slate-50 text-slate-500"><input :disabled="!['desktop', 'laptop'].includes(category)" name="specs[{{ $key }}]" value="{{ $value }}" placeholder="ระบุ {{ strtoupper($key) }}" class="rounded-xl"></div>@endforeach</div></div>
        <div><label class="mb-1 block text-sm font-semibold text-slate-900" for="description">รายละเอียดและตำหนิ</label><textarea id="description" required name="description" placeholder="บอกรายละเอียดสินค้า สภาพการใช้งาน และตำหนิ" class="min-h-28 w-full rounded-xl">{{ old('description', $product->description) }}</textarea></div>
        <div><label class="mb-1 block text-sm font-semibold text-slate-900">สถานะ</label><select name="status" class="rounded-xl"><option value="hidden" @selected(old('status', $product->status ?? 'hidden') === 'hidden')>ซ่อนสินค้า</option><option value="available" @selected(old('status', $product->status) === 'available')>พร้อมขาย</option></select></div>
        @if ($copiedImages->isNotEmpty())
            <section aria-labelledby="copied-images-heading" class="rounded-xl border border-slate-200 bg-slate-50 p-4"><h2 id="copied-images-heading" class="font-semibold text-slate-900">รูปที่จะคัดลอก ({{ $copiedImages->count() }} รูป)</h2><p class="mt-1 text-sm text-slate-600">รูปเหล่านี้จะถูกใช้กับรายการใหม่โดยอัตโนมัติ</p><div class="mt-3 flex flex-wrap gap-3">@foreach($copiedImages as $index => $image)<input type="hidden" name="copied_image_ids[]" value="{{ $image->id }}"><img src="{{ $image->image_url }}" alt="รูปสินค้าที่คัดลอก {{ $index + 1 }}" width="96" height="72" loading="lazy" class="h-20 w-24 rounded-lg border border-slate-200 object-cover">@endforeach</div></section>
        @endif
        <div class="rounded-xl border border-dashed border-red-500/60 bg-red-500/10 p-4"><label for="image_files" class="block font-semibold text-slate-900">แนบรูปจากคอมพิวเตอร์ <span class="font-normal text-slate-500">(ไม่บังคับ)</span></label><p id="image_files_help" class="mt-1 text-sm text-slate-500">รูปจะถูกจัดเก็บในระบบ เลือกได้สูงสุด 8 รูป: JPG, PNG หรือ WEBP รูปละไม่เกิน 5MB</p><input id="image_files" type="file" name="image_files[]" accept="image/jpeg,image/png,image/webp" multiple aria-describedby="image_files_help" class="mt-3 block w-full text-sm">@error('image_files')<p class="mt-1 text-xs text-red-400">{{ $message }}</p>@enderror @error('image_files.*')<p class="mt-1 text-xs text-red-400">{{ $message }}</p>@enderror</div>
        <button class="btn-primary">บันทึกสินค้า</button>
    </form>
</x-app-layout>
