<x-app-layout>
    <x-slot name="header"><div class="page-shell flex flex-wrap items-center justify-between gap-4"><div><p class="eyebrow">รายการสินค้าร้านค้า</p><h1 class="mt-1 font-bold text-2xl text-slate-900">สินค้าของร้าน</h1></div><a href="{{ route('dealer.products.create') }}" class="btn-primary">+ เพิ่มสินค้า</a></div></x-slot>
    <div class="page-shell py-8">
        <form method="GET" action="{{ route('dealer.products') }}" class="dealer-product-search">
            <div class="min-w-0 flex-1"><label for="dealer_product_search" class="mb-2 block text-sm font-bold text-slate-900">ค้นหาสินค้าในร้าน</label><input id="dealer_product_search" name="search" value="{{ $search }}" type="search" enterkeyhint="search" placeholder="ชื่อสินค้า" class="min-h-12 w-full rounded-xl" aria-describedby="dealer_product_search_help"><p id="dealer_product_search_help" class="mt-2 text-xs text-slate-400">ค้นหาได้จากชื่อสินค้า</p></div><button class="btn-primary min-w-28" type="submit">ค้นหา</button>@if($search)<a href="{{ route('dealer.products') }}" class="btn-secondary min-w-24">ล้าง</a>@endif
        </form>
        <p class="mt-5 text-sm text-slate-400">พบสินค้า {{ $products->count() }} รายการ@if($search) สำหรับ “{{ $search }}”@endif</p>
        <div class="mt-4 overflow-x-auto rounded-xl bg-white shadow"><table class="w-full text-left"><thead class="bg-gray-50 text-sm"><tr><th class="p-4">สินค้า</th><th>ราคา</th><th>คงเหลือ</th><th>สถานะ</th><th></th></tr></thead><tbody>@forelse($products as $product)<tr class="border-t"><td class="p-4"><b>{{ $product->name }}</b></td><td>฿{{ number_format($product->price,2) }}</td><td>{{ $product->stock_quantity }}</td><td>{{ $product->status === 'sold' ? 'ขายแล้ว' : ($product->status === 'reserved' ? 'จองแล้ว' : ($product->stock_quantity === 0 ? 'สินค้าหมด' : $product->status)) }}</td><td>@if($product->status === 'sold')<a class="text-indigo-600" href="{{ route('dealer.products.duplicate', $product) }}">สร้างรายการใหม่</a>@elseif($product->status === 'reserved')<span class="text-sm font-semibold text-slate-400">แก้ไขไม่ได้</span>@else<a class="text-indigo-600" href="{{ route('dealer.products.edit',$product) }}">แก้ไข</a>@endif</td></tr>@empty<tr><td class="p-5 text-gray-500" colspan="5">ไม่พบสินค้าที่ค้นหา</td></tr>@endforelse</tbody></table></div>
    </div>
</x-app-layout>
