<x-app-layout>
    <x-slot name="header"><div class="page-shell"><p class="eyebrow">Control center · Demo</p><h1 class="mt-1 text-2xl font-bold text-slate-900">แผงผู้ดูแลระบบ</h1></div></x-slot>
    <div class="page-shell py-8 sm:py-10">
        <section class="admin-hero"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-red-300">Marketplace command center</p><h2 class="mt-2 text-2xl font-bold text-white sm:text-3xl">ภาพรวมระบบสำหรับการนำเสนอ</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-slate-300">ตรวจสอบ KYC สลิป การถอนเงิน และข้อพิพาทจากจุดเดียว ข้อมูลในหน้านี้เป็นสถานการณ์ตัวอย่างสำหรับเดโม</p></div><span class="admin-shield" aria-hidden="true">⌘</span></section>
        <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="admin-stat"><span>ผู้ใช้งานทั้งหมด</span><strong>{{ number_format($stats['users']) }}</strong><small>บัญชี</small></article><article class="admin-stat"><span>สินค้าพร้อมขาย</span><strong>{{ number_format($stats['products']) }}</strong><small>รายการ</small></article><article class="admin-stat"><span>คำสั่งซื้อ</span><strong>{{ number_format($stats['orders']) }}</strong><small>บิล</small></article><article class="admin-stat admin-stat-sales"><span>ยอดชำระสำเร็จ</span><strong>฿{{ number_format($stats['sales'], 0) }}</strong><small>เดโม</small></article></section>
        <section class="demo-flow mt-8"><div><p class="eyebrow">Demo flow</p><h2 class="mt-1 text-xl font-bold text-slate-900">ลำดับการสาธิตระบบ</h2></div><ol><li><span>1</span>ลูกค้าเลือกสินค้าและเพิ่มลงตะกร้า</li><li><span>2</span>สแกน QR จำลองและแนบสลิป</li><li><span>3</span>ร้านค้ายืนยันสลิปและส่งพัสดุ</li><li><span>4</span>ลูกค้ายืนยันรับสินค้า รีวิว หรือเปิดข้อพิพาท</li></ol></section>
        <section class="mt-8 grid gap-5 xl:grid-cols-2">
            <article class="admin-panel"><div class="admin-panel-heading"><div><p class="eyebrow">KYC</p><h2>คำขอร้านค้า</h2></div><span class="admin-badge">{{ $profiles->count() }} รอจัดการ</span></div>@forelse($profiles as $profile)<div class="admin-row"><div><b>{{ $profile->store_name }}</b><p>{{ $profile->user->email }}</p></div><form class="flex gap-2" method="POST" action="{{ route('admin.kyc.update', $profile) }}">@csrf @method('PATCH')<button name="status" value="approved" class="admin-action admin-action-ok">อนุมัติ</button><button name="status" value="rejected" class="admin-action">ปฏิเสธ</button></form></div>@empty<p class="admin-empty">ไม่มีคำขอค้าง</p>@endforelse</article>
            <article class="admin-panel"><div class="admin-panel-heading"><div><p class="eyebrow">Dispute</p><h2>ข้อพิพาทสินค้า</h2></div><span class="admin-badge">{{ $disputes->count() }} รอตรวจสอบ</span></div>@forelse($disputes as $dispute)<div class="admin-row admin-row-stack"><div><b>{{ $dispute->orderItem->product->name }}</b><p>{{ $dispute->reason }}</p></div><form class="flex gap-2" method="POST" action="{{ route('admin.disputes.update', $dispute) }}">@csrf @method('PATCH')<button name="status" value="reviewing" class="admin-action">ตรวจสอบ</button><button name="status" value="resolved_refund" class="admin-action admin-action-ok">คืนเงิน</button></form></div>@empty<p class="admin-empty">ไม่มีข้อพิพาทค้าง</p>@endforelse</article>
        </section>
    </div>
</x-app-layout>
